# Generated by Django 4.0.3 on 2022-03-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='feature_collections',
            new_name='feature_collection',
        ),
    ]
