# Generated by Django 4.0.3 on 2022-03-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_feature_collections_usergroup_feature_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapboxStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapbox_id', models.CharField(max_length=512)),
            ],
        ),
    ]
