# Generated by Django 4.0.3 on 2022-03-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mapboxstyle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapboxStyle',
        ),
    ]
